version: 2.1

orbs:
  newman: postman/newman@dev:0.0.3

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3
  newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3
          environment: ./newman-orb.postman_environment.json
          timeout: "1000"
          insecure: true

workflows:
  newman-workflow:
    jobs:
      - newman-collection-run
      - newman-collection-run-env-timeout