version: 2.1
orbs:
  newman:
    executors:
      newman_docker:
        docker:
          - image: postman/newman_alpine33:4.1.0
    jobs:
      collection_run_from_url:
        executor: newman_docker
        parameters:
          url:
            type: string
        steps:
          - run: "newman run <<parameters.url>>"

workflows:
  newman-test:
    jobs:
      - newman/collection_run_from_url:
          name: "sample collection run"
          url: https://www.getpostman.com/collections/1d24d0cd53882ad791f3