version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  newman-collection-run:
    executor:
      name: newman/postman-newman-docker
      tag: 4.4.1
    steps:
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3

  newman-collection-run-verbose:
    executor:
      name: newman/postman-newman-docker
      tag: 4.4.1
    steps:
      - checkout
      - newman/newman-run:
          collection: ./postman-echo.postman_collection.json
          additional-options: "--verbose"

  newman-collection-run-env-timeout:
    executor:
      name: newman/postman-newman-docker
      tag: 4.4.1
    steps:
      - checkout
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3
          environment: ./newman-orb.postman_environment.json
          timeout: "1000"
          insecure: true

workflows:
  newman-workflow:
    jobs:
      - newman-collection-run
      - newman-collection-run-verbose
      - newman-collection-run-env-timeout