version: 2.1

orbs:
  newman: postman/newman@dev:0.0.1

jobs:
  newman-collection-run:
    executor: newman/docker-newman-alpine
    steps:
      - newman/collection-run:
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3
          options: >
            --environment=./newman-orb.postman_environment.json
            -n 2

workflows:
  newman-test-workflow:
    jobs:
      - newman-collection-run