version: 2.1
orbs:
  newman:
    executors:
      newman-docker:
        docker:
          - image: postman/newman_alpine33:4.1.0
    jobs:
      collection-run-with-environment:
        executor: newman-docker
        parameters:
          collection:
            description: "Collection file path or URL"
            type: string
          environment:
            description: "Environment file path or URL"
            type: string
        steps:
          - checkout
          - run: "newman run <<parameters.collection>> --environment=<<parameters.environment>>"

workflows:
  newman-test:
    jobs:
      - newman/collection-run-with-environment:
          name: '1'
          collection: https://www.getpostman.com/collections/1d24d0cd53882ad791f3
          environment: ./newman-orb.postman_environment.json